version: '3.8'

services:
  server:
    image: 'nginx:stable-alpine'
    ports: 
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  php:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      # :delegated flag for optimization
      - './src:/var/www/html:delegated' 
  mysql:
    image: 'mysql:5.7'
    env_file: 
      - './env/mysql.env'
  composer:
  # docker-compose run --rm composer create-project --prefer-dist laravel/laravel .
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - './src:/var/www/html' 
  # artisan:
  # npm: